// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "rest_api/domain"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeRepository is an autogenerated mock type for the EmployeeRepository type
type EmployeeRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, e
func (_m *EmployeeRepository) Save(ctx context.Context, e []*domain.Employee) error {
	ret := _m.Called(ctx, e)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Employee) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
