// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "rest_api/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, o
func (_m *OrderRepository) Save(ctx context.Context, o []*domain.Order) error {
	ret := _m.Called(ctx, o)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
