// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "rest_api/domain"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, p
func (_m *ProductRepository) Save(ctx context.Context, p []*domain.Product) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
