// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "rest_api/domain"

	mock "github.com/stretchr/testify/mock"
)

// ShippingMethodRepository is an autogenerated mock type for the ShippingMethodRepository type
type ShippingMethodRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, sm
func (_m *ShippingMethodRepository) Save(ctx context.Context, sm []*domain.ShippingMethod) error {
	ret := _m.Called(ctx, sm)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.ShippingMethod) error); ok {
		r0 = rf(ctx, sm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
